### ISSUE TITLE
Código morto / comentado	Código morto (nunca acessado ou usado)

### ISSUE THREAD

**Issue by eduardomarossi** [Fogelman/APS2_EMB#8]
https://github.com/Fogelman/APS2_EMB/blob/dbfe3a2ab533645408b6b2e6f3ea33dbec402ade/MXT_EXAMPLE_USART1/src/main.c#L293-L304

Ideal seria remover e recuperar via git se necessário

**Comment by wesleygas** [comment]
f2f67eb

Código removido
